name: Deploy Skystrim

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Build production bundle
        run: npm run build

      - name: Deploy to D:\Skystrim
        shell: powershell
        run: |
          # Путь к локальной сборке
          $distDir   = Join-Path $env:GITHUB_WORKSPACE 'dist'
          # Путь на сервере
          $targetDir = 'D:\Skystrim'
          # Синхронизируем файлы
          robocopy $distDir $targetDir /MIR /Z /NP /R:3 /W:5
          # Копируем public отдельно
          robocopy (Join-Path $env:GITHUB_WORKSPACE 'public') (Join-Path $targetDir 'public') /MIR /Z /NP /R:3 /W:5

      - name: Restart IIS App Pool
        shell: powershell
        run: |
          Import-Module WebAdministration
          Restart-WebAppPool -Name 'Skystrim'
